<!DOCTYPE html>
<html lang="en">

<title>PHYS S-12: Intro to Digital Fabrication </title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="../style.css" rel="stylesheet">

<body>


<xmp theme="journal" style="display:none;">



  # Week 2: 2D Design & Cutting

   For the second week, and offical first assignment of Digital Fabrication class, we were tasked with sketching and cutting out a 2D Press- Fit Kit with cardboard, following a Fusion360 tutorial, and recreating two household objects then using them in an assembly. For the kit, the only two requirements we were given happened to be: the model has to be interchangeable/assembled in different ways, and we must take into account the lasercutter kerf or, the difference between the outside measurements vs. the inside measurements once a piece is cut. With this said, I started with the press- fit kit.

   Some Helpful Vocabulary:

   Extrude: To add height to a 2D object, making it 3D

   Parameters: Set measurements for design elements

   Caliper: A device used to measure the dimenions of things related to your model. (Majority of the measurements such as kerf and thickness are done with a caliper)



   ## Flower Press- Fit Kit


   In class we briefly learned how to use the software Fusion360 to create our first 2D model of a square with notches. Once completing the in class tutorial, we were given the creative liberty to figure out what we wanted to do for our own Assembly Kits. I had many ideas however, the chosen one was interchangeable flowers. As a beginner, this was the inital drawing of the shape I wanted.


  ![Image of first drawing draft](./Draft.png)


  After deciding on the shape, I opened Fusion360 and created a new sketch. I selected the XY 2D plane on the bottom and chose my shape with the create button, which was a circumscribed polygon with 8 sides. I then set my parameters.

  Edge Length: 20mm 

  Notch Length: 10mm 

  Thickness: 3.5mm

  Kerf: 0.4mm


![Image of parameter](./Flower_Parameter.png)

![Image of inital measurement](./Inital_Measurement.png)

In order to get the correct size of the notch, I used a guided contruction line to split one of the sides in half. Then, I created half of the width for the notch by dividing the thickness by 2 and subtracting the kerf. This left me with 1.90mm for half of the thickness. For the length of the notch I measured a 10mm line from the outer edge of one of the sides drawing it inward.

![Image of half of the notch](./Before_Flipped.png)

Afterwards I was able to mirror the two lines using the same construction line and the mirror tool in order to get the full picture of one of the completed notches. 

![Image of mirrored notch](./Full_Notch_One_Side.png)


I then added the same notch to the rest of the 7 sides with the circular pattern button under the create tab, I entered in the number 8 as my shape had 8 sides.


![Image of all of the notches](./Notch_Flower.png)


After creating all of the notches I highlighted the main image and extruded it by 4mm by typing "E". Once the basic shape was done, I exported the file as a DXF and took my flashdrive to the FabLab to use the laser cutter, to bring it to life. 


![Image of extruded flower](./Extruded_Flower.png)


The final product resulted in a simple but successful piece. The take away for this project would be to be a little more ambitious. For the first project I decided to play it safe but, next time I will try to make things more interesting!


![Image of newly printed flower](./Single_Flower.jpeg) ![Image of together flowers](./TriFlower.jpeg)


![Image of a chain of flowers](./Chain_Flower.jpeg)



## Following A Tutorial

Alongside our project we were tasked with following an aditional tutorial that would help us continue to hone our skills with Fusion360 for future projects. If you are also like me, a beginner, I reccomend this tutorial (https://youtu.be/hko6q5jm_EY) by Gough Custom on youtube. That is what I used to recreate this lego brick! Here's what I did!

The first thing to do is create a sketch. You want to click on the bottom XY plane as, accoding to Gough Custom, will lie flat like a piece of paper. Then you want to press the 2 point rectangle buttom and draw any sized rectangle. With the sketch dimension feature you can click on one of the sides to add your dimensions. For the lego, the tutorial reccomeneded 5 inches, or 127mm, for the length of the rectangle and 3 inches, or 76.20mm, for the width.


![Image of basic lego dimensions](./Simple_Rectangle.png)


Then, by clicking finish sketch, you are able to create a 3D object out of the 2D drawing by extruding the sketch. This lego's heights is 2 inches or 50.8mm so that will be the amount you extrude the rectangle.


![Image of the extruded rectangle](./Brick.png)


Next, once you have an object that resembles a brick, you can click finish sketch and create a new one in the same tab. When you have the option to choose your plane, you can select the top of the model to start adding the lego pieces. The diameter of one circle is 1 inch or 25.4mm. You can ajust your circles in relation to the top of the rectangle with the sketch dimension tool. Take the point from the center of the circle and drag the dimension line to the outer ege of the rectangle for both sides, mark the line as 0.75 inches or 19.05mm.


![Image of the lego overhead](./Overhead.png)

![Image of the lego piece dimensions](./Circle_Dimensions.png)


After creatig the circle, you can highlight and extrude it by 0.25 inches or 6.35mm to give it the correct height.


![Image of the lego piece](./One_Prong.png)


To create 6 of these lego circles you can hit the create tab and select rectangular pattern. Change the type from faces to features and select the nub as an object. Then for the directions since the piece needs to be aligned with the outer egde click the on outer edge and then drag it across so there are three of them. Do the same process for the other direction highlighting all three this time, and set the quantity to 2 in order to have 6 extruded circles.


![Image of the 3 circled lego piece](./Three_Prong.png)

![Image of the complete lego piece](./Six_Prong.png)


The underside of a lego brick is actually hollow in order for it to snap togetherwith other pieces so, to recreate that, create another sketch and change the view to bottom and pick offset. Click on one of the edges and offset the image by -0.25 inches or -6.35mm and choose finish sketch.


![Image of the offset bottom](./Offset.png)


Now, in order to hollow out the bottom, select the inner rectangle from the previous offset and extrude it by grabbing the arrow and pulling it down to where it just barely touches the top of the lego.


![Image of the hollow bottom](./Hollow.png)


One of the final steps, that everyone hates, is to use the fillet tool for the lego. This addition is the thing that causes people to be uncomfortable when stepping on them. Click on the modify tab then choose fillet and select all of the edges on the outside and the inside. Then set the dimensions for the fillet at 0.1 inches or 2.54mm. 


![Image of the fillet highlights](./Fillet_Lego.png)

![Image of the finished lego](./Finished_Lego.png)


Here is the finished lego! The take away from this project is that with constant practice success is very likely. With this tutorial I feel more confident when using Fusion360 and I realised I am capable of creating more things than I thought.



## Household Object Assignment

For this section of the assignment I decided to focus on putting multiple models together. While we were given the helpful resource of GrabCad, I had troubles trying to download and export the software. Therefore, I decided to go with something simple yet, have the finished product be as clean as possible, to the best of my ability. I chose my two hosehold objeects to be a water bottle, with the measurements roughly based off of the Harvard waterbottles we were given when we first arrived to summer school, along with a roll of masking tape I found in the lab. The measurements and inital set parameters are as follows:

Bottle Diameter: 70mm

Bottle Height Without Cap: 210mm

Cap Diameter: 57mm

Cap Height: 10mm

Tape Diameter: 105mm

Tape Hole Diameter: 75mm

Tape Thickness: 13mm

The first order of business was to start off with the water bottle. Using a caliper I recorded my measurements as referenced above and began to create a circle with the diameter of 70mm on the XY plane. I then extruded the figure to make the bottle's height of 210mm.


![Image of the bottle diameter](./Bottle_Measurements.png)

![Image of the extruded bottle](./Extruded_Bottle.png)


Then, I added the cap onto the bottle. I finished the first sketch, selected the top of the bottle (where the cap will go) and then created a circle with the same diameter as the cap, which was 57mm. I extruded the circle to have a height of 10mm. In order to make the bottle look tapered I used the fillet tool and selected the outer edge of the main bottle without the cap. The fillet went to 13mm. Afterwards, I further extruded the top of the bottle by 7mm by reselecting the cap. This was because the fillet resulted in the caps height looking shortened. The extra height allowed the water bottle to look more like the reference. 


![Image of the cap measurements](./Cap_Diameter.png)

![Image of the fillet bottle](./Fillet_Bottle.png)


After getting the shape I desired, I highlighted parts of the design that I wanted to color. I right clicked on the main body and scrolled until I found the right materials. All of the colors I used were already availble in the "Fusion360 Appearances" section of apperance. The colors and textures I used were, "Water- Clear" and "Orgasol Invent Smooth- PA 12" under the opeque plastics folder. For the cap the color I used the "Nylon 12 (with Formlabs Fuse 1 3D Printer)" option to click and drag the color onto it. This was the final result.


![Image of the colored bottle](./Colored_Bottle.png)


I saved the image under the name "WaterBottle" and continued on to make the more simple parts of my assembly. I chose to start on the masking tape. After openening another tab and creating a new design, I selected the famous XY plane and created a circle with a 105mm diameter. I then extruded the circle to have 13mm of thickness.


![Image of the tape measurements](./Tape_Sizes.png)

![Image of the extruded circle](./Tape_no_hole.png)


In order to make the masking tape look like masking tape, I used the hole function under the create tab. I clicked on the top of the circles surface and set the hole to be 75mm wide and the depth to be the same as the thickness of 13mm. This was the almost finished result.


![Image of the tape model](./Basic_Tape.png)


Once the basic shape of the tape model was formed I decided to color it. After scrolling and testing a few colors and textures I decided on "Acetal Resin (White)." I saved it under the name, "Masking_Tape"


![Image of the tape model](./Colored_Tape.png)


I decided I needed  way to connect these two items in an easy way that relates to my final project. The best way to do this was with a simple shelf. (Refer to my final project section of this portolio!) I again, created another sketch in a seperate tab and designed a rectangle with random measurements as I didnt know how much space the objects would take up. It was then extruded by 10mm. I saved it under the name "Shelf."


![Image of the extruded shelf](./Extruded_Shelf.png)


Now that I had every component seperately it was time to put them all together. I made sure my files were all saved and updated to the latest version. I started off with the shelf and clicked the insert button to insert derive. I started again with the water bottle and clicked on its file to transport the image to where the shelf was. I then highlighted and right clicked on the bottle's image to move position it on the corner of the shelf.


![Image of the bottle on the shelf](./Moving_Bottle.png)


I dragged the end of the shelf to extend it enough to make comfortable room for the masking tape. The length and width of the shelf now being 400mm by 260mm. I did the same thing to the masking tape, by clicking insert and inserting the derive. I also positioned it by right clicking and using the move button to slide it over. This was the final assembly.


![Image of the tape](./Moving_Tape.png)

![Image of the final shelf](./Final_Shelf.png)


The take away for me of this last part of the assignement was that choosing your items carefully can save you alot of trouble in the long run. I originally started off making drafts of 5 other objects and it would have saved me alot of time if I sat down to think about what I really wanted to do.

 Use this to go back to the homepage! [link](../index.html).

</xmp>
</body>

<script src="https://strapdownjs.com/v/0.2/strapdown.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" ></script>

</html>